services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: sebelas
      POSTGRES_PASSWORD: sebelas
      POSTGRES_DB: sebelas
    # JANGAN expose ke publik
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    # JANGAN expose ke publik
    # ports:
    #   - "6379:6379"

  api:
    build: ./apps/api
    env_file: ./apps/api/.env
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - postgres
      - redis

  admin-web:
    build: ./apps/admin-web
    env_file: ./apps/admin-web/.env
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - api

  store-web:
    build: ./apps/store-web
    env_file: ./apps/store-web/.env
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - api

volumes:
  postgres_data:
